### ISSUE TITLE
I/O: `Read::bytes()` is very slow, even on a `BufReader`

### ISSUE THREAD

**Issue by Shnatsel** [nnethercote/perf-book#69] opened 2023-10-07 10:55 UTC
The performance of [`Read::bytes()`](https://doc.rust-lang.org/stable/std/io/trait.Read.html#method.bytes) iterator is atrocious, even over a `BufReader`.

Here's a sample program calculating a sum of all bytes in the file with various approaches:
- [Read::bytes()](https://github.com/Shnatsel/fast-io-cookbook/blob/8db6420c8090f291d2643d30edbf9c1a9a923f02/src/bin/bytes.rs)
- [fs::read()](https://github.com/Shnatsel/fast-io-cookbook/blob/8db6420c8090f291d2643d30edbf9c1a9a923f02/src/bin/fs_read.rs)
- [Manual loop over an unbuffered `Read::read()`](https://github.com/Shnatsel/fast-io-cookbook/blob/8db6420c8090f291d2643d30edbf9c1a9a923f02/src/bin/manual_read.rs)

In this test `Read::bytes()` 10x slower than reading the whole file into memory up front and 20x slower than manually reading into a smallish buffer over and over. The performance gap is so large that even reading line-by-line with UTF-8 validation is still multiple times faster!

Benchmarked using [`hyperfine`](https://crates.io/crates/hyperfine) on [this public domain book](https://www.gutenberg.org/ebooks/71375) in plain text format repeated 50 times.

**Comment by nnethercote** [comment] 2023-10-11 22:54
I found there's a bug in your third program, which causes it to give different answers to the first two programs for any file with more than 64 KiB chars. The problem is that on the final iteration `chunk` is only partially filled with new data, but the program sums all the elements within it, which includes some old ones from the second-last iteration.

Here's a version that uses `take` to fix the problem, and also avoids having two `test_file.read()` calls. It seems to give similar performance to the original version.
```rust
use std::io::Read;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let test_file_path = std::env::args_os().nth(1).expect("No input file specified!");
    
    let mut test_file = std::fs::File::open(test_file_path)?;

    // Instead of reading the whole file in memory, read it in small-ish chunks that fit into CPU
    // cache. This also dramatically reduces memory usage because we never keep more than 64 KiB in
    // memory.
    let mut chunk = vec![0; 65536];
    let mut sum: u64 = 0;
    loop {
        let bytes_read = test_file.read(&mut chunk)?;
        if bytes_read == 0 {
            break;
        }
        sum += chunk.iter().take(bytes_read).map(|i| *i as u64).sum::<u64>();
    }
    
    println!("{sum}"); 
    Ok(()) 
}
```

**Comment by Shnatsel** [comment] 2023-10-11 23:05
Good catch! Thanks!

There may be some bugs like these lurking still, I didn't do any in-depth testing yet. The fully manual *line* reader is definitely buggy, but probably not in ways that matter for performance.

I've adopted your version of the manual read loop, only changing `chunk.iter().take(bytes_read)` to `chunk[..bytes_read].iter()` so that it *definitely* doesn't introduce an extra branch for every element. It would be a pretty bad optimization gaffe if it ever did in this example, but for long iterator chains - who knows!

**Comment by nnethercote** [comment] 2023-10-12 07:00
I filed https://github.com/rust-lang/rust/pull/116651 which speeds up `Read::bytes` quite a bit, though it's still a lot slower than the alternatives. And I added some explanation of this to its docs.

**Comment by Shnatsel** [comment] 2023-10-12 11:08
Oh, that's amazing! I didn't expect my observations to lead to actual speedups!

I cannot wrap my head about why that transformation makes the code faster. How does reading into a struct member instead of a local variable speed things up?

**Comment by nnethercote** [comment] 2023-10-20 06:51
Now that https://github.com/rust-lang/rust/pull/116775 and https://github.com/rust-lang/rust/pull/116785 have landed, `Read::bytes` is competitive with alternative approaches, so I don't think we need to document anything in the perf book. Thanks for the suggestion, that was a productive exercise :)

**Closed by nnethercote** 2023-10-20 06:51 UTC
